apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskdemo
  labels:
    app: flaskdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskdemo
  template:
    metadata:
      labels:
        app: flaskdemo
    spec:
      containers:
      - name: flaskdemo
        image: acrk8sdemoappdev.azurecr.io/images:app-19
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flaskdemo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: flaskdemo
