replicaCount: 1

image:
  repository: acrk8sdemoappdev.azurecr.io/images
  tag: "app-27"  # Ten tag jest automatycznie aktualizowany przez pipeline

service:
  name: flask-service
  type: LoadBalancer
  port: 80
  targetPort: 5000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"